# Generated by Django 4.0.3 on 2022-04-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covid',
            old_name='total_recorder',
            new_name='total_recovered',
        ),
    ]
