# Generated by Django 4.0.3 on 2022-04-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_total_recorder_covid_total_recovered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='total_cases',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='total_deaths',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='total_recovered',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
